version: '3.9'
services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper
    volumes:
      - shopper_pg_data:/var/lib/postgresql/data

volumes:
  shopper_pg_data:
